[project]
name = "silentcipher-demo"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "flask>=2.2.5",
    "silentcipher>=1.0.2",
]

[dependency-groups]
dev = [
    "ipykernel>=6.29.5",
]
