AUDIO_LEN: 12
A_weighting: false
HOP_LENGTH: 1024
NMR: 0.0
N_FFT: 2048
SR: 16000
TEMP_PATH: /group/project25/Mayank/Models/HideAndSpeak/ablate_beat_wavmark_47dB/negative_message_50_percent/temp_files/
TEST_AUDIO_LEN: 12
aac_aug: false
add_carrier_noise: gaussian
adv: false
batch_size: 4
block_type: normal
carrier_detach: -1
carrier_noise_norm: 0.01
cdpam_metric: false
curriculum: 0
dataloader_length: 189
dataset: vctk
dataset_based_SDR: false
dec_c_n_layers: 4
decoder_access_source: false
enc_n_layers: 3
encoder_decide_SDR: false
ensure_constrained_message: false
ensure_negative_message: true
frame_level_normalization: false
lambda_carrier_loss: 20.0
lambda_msg_loss: 20.0
load_ckpt: /group/project25/Mayank/Models/HideAndSpeak/ablate_beat_wavmark_47dB/negative_message/ckpt/81560_iteration
loss_type: mse
lr: 0.001
mel_loss: 0
message_band_size: 512
message_dim: 4
message_len: 16
message_sdr: 47
microphoneEQ: false
mix_train: false
mode: train
model_type: n_msg
mp3_aug: false
msg_loss_weighting_with_energy: false
n_messages: 1
no_normalization: false
num_iters: 5
num_workers: 8
ogg_aug: false
opt: adam
otat: false
phase_shift: null
remove_heuristic_message: false
rir: /group/project25/Mayank/RIR/rir_small.wav.npz
rir_train: false
run_dir: /group/project25/Mayank/Models/HideAndSpeak/ablate_beat_wavmark_47dB/negative_message_50_percent
sample_every: null
save_model_every: null
seed: 0
stft: new_stft
test_path: Data/test.txt
test_results_path: Results/results
train_path: Data/train.txt
utterance_level_normalization: true
val_path: null
